---

- name: (basic-auth) ensure apache2-utils is installed
  become: yes
  apt:
    name: apache2-utils

- name: (basic-auth) create htpasswd file
  become: yes
  shell: 'htpasswd -cb /etc/nginx/.htpasswd {{ nginx_basic_auth_username }} {{ nginx_basic_auth_password }}'
  when:
    - nginx_basic_auth_username is defined
    - nginx_basic_auth_password is defined

