---
- name: create build directory
  file:
    path: '../production/build'
    state: directory

- name: 'Build image {{ item.name }} local and archive'
  docker_image:
    name: 'hute/{{ item.name }}:latest'
    archive_path: '../production/build/{{ item.name }}.tar'
    build:
      pull: no
      dockerfile: '{{ item.dockerfile }}'
      path: '../..'
    source: build
    force_source: yes
    state: present
