---
- name: 'Check if {{ item.name }} is running'
  docker_container_info:
    name: '{{ item.name }}'
  register: 'container_state'

- name: 'Remove running container'
  docker_container:
    name: '{{ item.name }}'
    state: absent
    container_default_behavior: 'compatibility'
  when: 'container_state.exists'

- name: 'Pull image'
  docker_image:
    name: "{{ item.image }}"
    source: pull
    state: present
    force_source: yes
  when:
    - local is undefined 
    - item.state != 'absent'

- name: 'Build image'
  docker_image:
    name: "{{ item.image }}"
    state: present
    source: build
    force_source: yes
    build:
      dockerfile: "{{ item.dockerfile }}"
      path: "../.."
      pull: no
  when: 
    - local is defined 
    - item.state != 'absent'

- name: 'Ensure {{ item.name }} is {{ item.state }}'
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    state: "{{ item.state }}"
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: hute-net
    container_default_behavior: 'compatibility'
    published_ports:
      - '{{ item.port_host }}:{{ item.port_container }}'
  when: item.state != 'absent'
