---
- name: 'Check if {{ item.name }} is running'
  docker_container_info:
    name: '{{ item.name }}'
  register: 'container_state'

- name: 'Remove running container'
  docker_container:
    name: '{{ item.name }}'
    state: absent
    container_default_behavior: 'compatibility'
  when: 'container_state.exists'

- name: 'Remove old image'
  docker_image:
    name: 'hute/{{ item.name }}:latest'
    state: absent

- name: 'Pull image'
  docker_image:
    name: "{{ item.image }}"
    source: pull
    state: present

- name: 'Run container'
  docker_container:
    name: '{{ item.image }}'
    image: 'hute/{{ item.name }}:latest'
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: hute-net
    container_default_behavior: 'compatibility'
    published_ports:
      - '{{ item.port_host }}:{{ item.port_container }}'

- name: 'Ensure container is running'
  docker_container:
    name: '{{ item.name }}'
    state: "{{ item.state | default('started') }}"
    container_default_behavior: 'compatibility'
