---
##########################
# USERS
##########################

linux_groups:
  - groupname: ssh_access
  - groupname: no_pwd_sudoers

linux_users:
  - username: hute
    generate_ssh_key: no
    groups:
      - ssh_access
      - no_pwd_sudoers
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK7McHH/C6GTuB8RFwqxGdZZaZK7zAFgLh/p5B2ru3mqPOfM8qu+mjiTkCmhd+gNrM+3UCrJop/cWh0uW1cLPpP43XJujbUgFjx4t24w/7rmy5l0yECUfGHbLNUKMgk/4TwAiShG3/Ov2MnvR+q1wopN+/Ncoh3QMe/cDQ09afwbdqMMAzluTwwl6zCdesWUS4Nn/Rxno9SOs5hnVadiBwXhM1n6jy+O4fXgV/JrPrvnpOpkyyOaAU1PAugB+dsCDZGMIiGQYjIznIu53LyFD3Y3t5VNwNB8aD/gW0xfqiL9ovu+OiVMLvGl7Wv2O3WreW5GtXLigOSjsr/PZXlhwTb1g0ouD2VhYpwFy17asnkHHPnJ1PYoFmM1k7L8VTfUxgvRalL5M7NYUxxKF11dxgo1eERiozF5D8Ew4mB1NsQWrjNJ9+lRNRgiWTm1GsQly+kemSxw29m0lbX0fLofe59iw42gPk4pz49tAkhxCZr0PGsHGaW7iRpC0tZvJh7xE= hute
"
  
docker_users:
  - hute

##########################
# SERVER SECURITY
##########################

ssh_port: "44"
ssh_allow_groups: ssh_access

ufw_rules:
  - port: 80
    rule: allow
    proto: tcp
  - port: 443
    rule: allow
    proto: tcp

