---
- hosts: server

  vars:
    - nginx_conf: '/home/hute/nginx.conf'
    - certbot_email: webmaster@hute.info

  tasks:
    - name: Setup network
      docker_network:
        name: hute-net
        state: "{{ hute_net_state | default('present') }}"

    - name: Copy files to remote
      copy:
        src: '{{ item }}'
        dest: '/home/hute'
      with_fileglob:
        - './files/*'

    - name: Ensure db are running
      include_tasks: ../tasks/db.yml
      loop:
        - {
            name: 'hute-db',
            port: '25432',
            db: 'hute',
            user: 'hute',
            password: 'hute',
            data_store: 'hute-db-datastore',
            init_sql: '/home/hute/init.sql',
            state: 'started',
          }

    - name: Deploy server
      include_tasks: ../tasks/deploy.yml
      loop:
        - { 
            name: 'hute-app', 
            dockerfile: 'Dockerfile.app', 
            image: 'hute/hute-app:latest', 
            port_host: '3000', 
            port_container: '3000',
            state: started
          }
        - { 
            name: 'hute-server',
            dockerfile: 'Dockerfile.server',
            image: 'hute/hute-server:latest',
            port_host: '4000',
            port_container: '4000',
            state: started 
          }

    - name: Ensure nginx is running
      include_tasks: ../tasks/nginx.yml

    - name: Prune all unused images
      docker_prune: 
        containers: yes
        images: yes
      