---
- hosts: localhost
  connection: local

  vars:
    - local: yes
    - nginx_conf: './files/nginx.conf'

  tasks:
    - name: Setup network
      docker_network:
        name: hute-net
        state: "{{ hute_net_state | default('present') }}"

    - name: Ensure db is running
      include_tasks: ../tasks/db.yml
      loop:
        - {
            name: 'hute-db',
            port: '25432',
            db: 'hute',
            user: 'hute',
            password: 'hute',
            data_store: 'hute-db-datastore',
            init_sql: '../../scripts/init.sql',
          }

    - name: Deploy server
      include_tasks: ../tasks/deploy.yml
      loop:
        # - { name: 'hute-app', dockerfile: 'Dockerfile.app', port_host: '3000', port_container: '3000' }
        - { name: 'hute-server', dockerfile: 'Dockerfile.server', port_host: '4000', port_container: '4000' }

    - name: Ensure nginx is running
      include_tasks: ../tasks/nginx.yml
