---
- name: start db
  hosts: localhost

  tasks:
    - name: Setup network
      docker_network:
        name: hute-net
        state: "{{ hute_net_state | default('present') }}"

    - name: Ensure dbs are pruned
      include_tasks: ../tasks/db-prune.yml
      loop:
        - { name: 'hute-db', data_store: 'hute-db-datastore' }
        - { name: 'hute-db-test', data_store: 'hute-db-test-datastore' }

    - name: Ensure dbs are running
      include_tasks: ../tasks/db.yml
      loop:
        - {
            name: 'hute-db',
            port: '25432',
            db: 'hute',
            user: 'hute',
            password: 'hute',
            data_store: 'hute-db-datastore',
            init_sql: '../../scripts/init.sql',
          }
        - {
            name: 'hute-db-test',
            port: '25433',
            db: 'hute',
            user: 'hute',
            password: 'hute',
            data_store: 'hute-db-test-datastore',
            init_sql: '../../scripts/init.sql',
          }
