---

- name: (sudo) install sudo
  become: yes
  apt:
    name: sudo

- name: (sudo) create no_pwd_sudoers group
  become: yes
  group:
    name: no_pwd_sudoers

- name: (sudo) add no_pwd_sudoers to /etc/sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%no_pwd_sudoers"
    line: "%no_pwd_sudoers ALL=(ALL:ALL) NOPASSWD:ALL"
