---

- name: (users) add users
  become: yes
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | join(',') }}"
    generate_ssh_key: "{{ item.generate_ssh_key }}"
  with_items: "{{ linux_users }}"
  when: linux_users | length > 0

- name: (users) authorize ssh key
  become: yes
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
  with_items: "{{ linux_users }}"
  when: linux_users | length > 0
