---

- name: "(ufw) check ufw package"
  become: yes
  apt:
    name: ufw

- name: "(ufw) configure open ports with ufw"
  become: yes
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ ufw_rules }}"
  when: ufw_rules | length > 0

- name: "(ufw) ensure ssh port is allowed"
  become: yes
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  when: ssh_port is defined

- name: "(ufw) configure default incoming/outgoing rules with ufw"
  become: yes
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - { direction: outgoing, policy: allow }
    - { direction: incoming, policy: deny }



