#https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf

name: Test feature branch

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  codestyle:
    runs-on: ubuntu-latest
    container: 
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build dependencies
        run: yarn --cwd app build
      - name: Run linter
        run: yarn lint
      - name: Run formatter
        run: yarn format

  test-server:
    runs-on: ubuntu-latest
    container:
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Ensure test db is running
        run: ansible-playbook infrastructure/local/docker-state.yml --extra-vars "container=db-test state=started"
      - name: connect to networkci
        run: docker network connect hute-net ${{ job.container.id }}
      - name: restart
        run: docker container start hute-db-test
      - name: run migrations
        run: yarn --cwd server run-migrations-testci
      - name: Run tests
        run: yarn --cwd server testci