name: Test feature branch

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

  workflow_dispatch:

jobs: 
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute action 
        uses: ./.github/actions/setup
        id: hello
        with: 
          who-to-greet: 'Hute'
      - name: Get output
        run: echo "THe time was ${{ steps.hello.outputs.time }}"