name: Test feature branch

on:
  # push:
    # branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  test-server:
    runs-on: ubuntu-latest

    container:
      image: hute/ci-base:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Execute action 
        # uses: ./.github/actions/setup
        # id: hello
        # with: 
          # who-to-greet: 'Hute'
      - name: Run tests
        run: ./hute start-test --ci