name: Build and deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  codestyle:
    runs-on: ubuntu-latest
    container: 
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build dependencies
        run: yarn --cwd app build
      - name: Run linter
        run: yarn lint
      - name: Run formatter
        run: yarn format

  test-server:
    runs-on: ubuntu-latest
    container:
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Ensure test db is running
        run: ansible-playbook infrastructure/local/docker-state.yml --extra-vars "container=db-test state=started"
      - name: connect to networkci
        run: docker network connect hute-net ${{ job.container.id }}
      - name: restart
        run: docker container start hute-db-test
      - name: run migrations
        run: yarn --cwd server run-migrations-testci
      - name: Run tests
        run: yarn --cwd server testci
    
  build-app:
    needs:
      - codestyle
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replace localhost in .env.prod 
        run: sed -i -e 's|/localhost:4000/|/hute.info/|g' .env.prod
      - name: Replace DB_PASSWORD in .env.prod 
        run: sed -i -e 's|DB_PASSWORD=hute|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|g' .env.prod
      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build server image
        run: docker build --tag hute/hute-app:latest --file Dockerfile.app .
      - name: Push to docker hub
        run: docker push hute/hute-app:latest 

  build-server:
    needs: 
      - test-server
      - codestyle
    runs-on: ubuntu-latest
    container: 
      image: hute/ci-base:latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replace localhost in .env.prod 
        run: sed -i -e 's|/localhost:4000/|/hute.info/|g' .env.prod
      - name: Replace DB_PASSWORD in .env.prod 
        run: sed -i -e 's|DB_PASSWORD=hute|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|g' .env.prod
      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build server image
        run: docker build --tag hute/hute-server:latest --file Dockerfile.server .
      - name: Push to docker hub
        run: docker push hute/hute-server:latest 

  deploy:
    needs: 
      - build-server
      - build-app
    runs-on: ubuntu-latest
    container:
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup ssh connection
        uses: webfactory/ssh-agent@v0.4.1
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy production
        run: ansible-playbook -i infrastructure/production/inventory infrastructure/production/deploy.yml
