
name: Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  test-server:
    runs-on: ubuntu-latest
    container:
      image: hute/ci-base:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Ensure test db is running
        run: ansible-playbook infrastructure/local/start-test-db.yml
      - name: connect to network
        run: docker network connect hute-net ${{ job.container.id }}
      - name: restart
        run: docker container start hute-db-test
      - name: Run migrations
        run: yarn --cwd server run-migrations-testci
      - name: Run tests
        run: yarn --cwd server testci